#!/usr/bin/env node
/*
 * Rasterize hand-crafted SVGs to .webp for Zenn (which does not accept SVG).
 *
 * Workflow (per diagram):
 *   1. Edit the Mermaid source of truth: mermaid/articles/<slug>/<n>-name.mmd
 *      (the .mmd holds the diagram's logic; kept in the repo but hidden from readers)
 *   2. Express it richly in svg/articles/<slug>/<n>-name.svg
 *      (generated by scripts/gen_diagrams.py; the replacement for the old .drawio step)
 *   3. Run this script to render svg/**.svg -> images/**.webp (Chrome @2x -> cwebp)
 *   4. The article references only the .webp
 *
 * Usage:
 *   node scripts/svg2webp.mjs                 # convert every .svg under svg/
 *   node scripts/svg2webp.mjs path/to/x.svg   # convert a single file
 *   node scripts/svg2webp.mjs svg/articles/slug
 *   mise run svg2webp                         # same as no arguments
 */
import { readFileSync, mkdirSync, readdirSync, statSync, rmSync } from 'node:fs';
import { dirname, join, relative, resolve, basename } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';
import puppeteer from 'puppeteer-core';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SCALE = Number(process.env.SCALE || 2);
const QUALITY = Number(process.env.QUALITY || 90);

function findChrome() {
  if (process.env.PUPPETEER_EXECUTABLE_PATH) return process.env.PUPPETEER_EXECUTABLE_PATH;
  const candidates = [
    '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
    '/Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary',
    '/Applications/Chromium.app/Contents/MacOS/Chromium',
    '/usr/bin/google-chrome',
    '/usr/bin/chromium',
    '/usr/bin/chromium-browser',
  ];
  for (const c of candidates) { try { statSync(c); return c; } catch {} }
  throw new Error('Chrome/Chromium not found. Set PUPPETEER_EXECUTABLE_PATH.');
}

function collect(target) {
  const st = statSync(target);
  if (st.isDirectory()) {
    const out = [];
    for (const e of readdirSync(target)) {
      if (e.startsWith('.')) continue;
      out.push(...collect(join(target, e)));
    }
    return out;
  }
  return target.endsWith('.svg') ? [target] : [];
}

const args = process.argv.slice(2);
const targets = args.length ? args.map((a) => resolve(a)) : [join(repoRoot, 'svg')];
const files = targets.flatMap(collect).sort();
if (!files.length) { console.error('No .svg files found.'); process.exit(1); }

const browser = await puppeteer.launch({
  executablePath: findChrome(),
  args: ['--no-sandbox', '--force-color-profile=srgb'],
});

for (const svgPath of files) {
  const svg = readFileSync(svgPath, 'utf8');
  const m = svg.match(/viewBox="0 0 ([\d.]+) ([\d.]+)"/);
  const w = m ? Math.round(parseFloat(m[1])) : 1200;
  const h = m ? Math.round(parseFloat(m[2])) : 800;

  const page = await browser.newPage();
  await page.setViewport({ width: w, height: h, deviceScaleFactor: SCALE });
  const htmlDoc = `<!doctype html><html><head><meta charset="utf-8">
    <style>*{margin:0;padding:0}html,body{background:transparent}
    svg{display:block}</style></head><body>${svg}</body></html>`;
  await page.setContent(htmlDoc, { waitUntil: 'networkidle0' });
  await new Promise((r) => setTimeout(r, 150)); // let emoji/fonts settle

  const rel = relative(join(repoRoot, 'svg'), svgPath).replace(/\.svg$/, '');
  const out = join(repoRoot, 'images', rel + '.webp');
  mkdirSync(dirname(out), { recursive: true });

  const tmpPng = out.replace(/\.webp$/, '.tmp.png');
  await page.screenshot({ path: tmpPng, omitBackground: true, clip: { x: 0, y: 0, width: w, height: h } });
  await page.close();

  execFileSync('cwebp', ['-quiet', '-q', String(QUALITY), tmpPng, '-o', out]);
  rmSync(tmpPng, { force: true });
  console.log(`\u2713 ${relative(repoRoot, svgPath)} -> ${relative(repoRoot, out)} (${w}x${h} @${SCALE}x)`);
}

await browser.close();
